name: toec2workflow
on: push 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the files
        uses: actions/checkout@v4

      - name: copy the code into the server 
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

  
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt update- -y
            sudo apt install apache2 -y
            sudo systemctl start apache2
            cd datadir
            sudo mv * /var/www/html
            
