name: workflow2
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: create a  container
        run: docker run -d --name=cont1 -p 8080:80 nginx
      - name: access the container 
        run: curl http://localhost:8080
        
